### ISSUE TITLE
How does the size of glyphs work?

### ISSUE THREAD

**Issue by IamTheCarl** [Penple/msdf-rs#2]
I'm new to font rendering so this may be an obvious misunderstanding on my side of things.
I am attempting to build a font renderer that first creates an atlas of MSDFs. This of course requires me to create many images of MSDFs with tight bounding boxes.

Using the ttf_parser crate I can load a font and gather information about the size of glyphs. For some reason, ttf_parser reports the size of glyphs being far bigger than the size msdf-rs renders them at. How does the scale of the MSDF compare to that of what ttf_parser reports? Is there a way to control the size msdf-rs renders at?

Here's an example of the letter A from the `Roboto-Medium.ttf` in this very repository.
According to (Face::glyph_bounding_box)[https://docs.rs/ttf-parser/0.15.2/ttf_parser/struct.Face.html#method.glyph_bounding_box] the glyph has the following dimensions:
```
[src/graphics/text.rs:52] &size = Rect {
    x_min: -37,
    y_min: -437,
    x_max: 1016,
    y_max: 1536,
}
```

But a 16x16 image produced by msdf-rs looks like this.
![258](https://user-images.githubusercontent.com/21977560/191296030-5027a872-582f-4f7e-b1b9-c954b3743364.png)

Clearly, msdf-rs is interpreting these numbers as something scaled down, although I don't what that factor is.

**Comment by Penple** [comment]
The [scale factor is 64](https://github.com/Penple/msdf-rs/blob/main/msdf/src/loader.rs#L11-L12).

This was done to match the behavior of the `msdfgen` command line utility, which acts differently to the `msdfgen` library. This behavior is [probably wrong](https://github.com/Chlumsky/msdfgen/issues/147), and I was planning on removing this scaling factor in a breaking v0.2.0 release. For the time being, you should be able to get around this by dividing the coordinates by `64.0`.

**Comment by IamTheCarl** [comment]
I had actually gotten very close to figuring this out through brute force guess and check (I was guessing about 65).
Thank you for that clarification. I'm looking forward to v0.2.0.

**Comment by Penple** [comment]
> Thank you for that clarification. I'm looking forward to v0.2.0.

v0.2.0 has been published and is available on crates.io. (and v0.2.1)
