### ISSUE TITLE
Incorrect Distance Fields

### ISSUE THREAD

**Issue by ElfWitch** [Penple/msdf-rs#7]
When I generate MSDFs with this library, the distance fields seem to be only masks. The values in each channel after running `MTSDF::render_colored()` are either 1.0 or 0.0.

This is what I mean:
![Screenshot 2023-05-27 014938](https://github.com/Penple/msdf-rs/assets/109904725/5f4be991-e156-4f07-900b-7613e8cd0ad1)

![Screenshot 2023-05-27 015058](https://github.com/Penple/msdf-rs/assets/109904725/59441e04-cb68-4b34-afda-968b4b1ff05b)

here is an example of the output from the RGBA32Image:
```
...

[
    0.0,
    1.0,
    0.0,
    0.0,
]
[
    0.0,
    1.0,
    0.0,
    0.0,
]
[
    0.0,
    1.0,
    0.0,
    0.0,
]
[
    0.0,
    1.0,
    0.0,
    0.0,
]
[
    0.0,
    1.0,
    0.0,
    0.0,
]

...

```

As you can see, there aren't any smooth gradients on the edges. I can't tell if this is an error on my part or if there is a bug in the library. Using the [msdfgen ](https://github.com/Chlumsky/msdfgen)command line utility produces correct distance fields.

**Comment by Penple** [comment]
It's unlikely that `::render_colored()` is what you're looking for here. `::render()` and `::render_colored()` are the functions provided by msdfgen to produce a rendered glyph from a MSDF. If you're looking to get the MSDF as an image (if you're going to render it yourself), you probably want to call `SDFTrait::to_image()` (or `SDFTrait::image()`). Also, make sure you're providing a sensible value for the `range` passed to `::generate_mtsdf()`.

**Comment by ElfWitch** [comment]
Wow thank you very much for the fast and helpful reply. I understand now, `SDFTrait::image()` was what I should have been using. 

It works now!
![image](https://github.com/Penple/msdf-rs/assets/109904725/a355beb8-30c1-40cb-adc4-b272fd0dd21a)
![image](https://github.com/Penple/msdf-rs/assets/109904725/87576472-c741-4039-b8ee-6d8ef49310ef)
